name: flutter_performance_pulse
description: A real-time performance monitoring toolkit for Flutter apps by jamalihassan0307. Track FPS, memory, CPU, network, and system metrics with visualizations.
version: 1.0.5
homepage: https://github.com/jamalihassan0307/flutter_performance_pulse
repository: https://github.com/jamalihassan0307/flutter_performance_pulse
documentation: https://github.com/jamalihassan0307/flutter_performance_pulse/blob/main/README.md

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # UI and Visualization
  fl_chart: ^0.70.2

  # System Monitoring
  device_info_plus: ^11.3.0
  battery_plus: ^6.2.1
  compute: ^1.0.2

  # Network and Storage
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
