name: flutter_performance_pulse
description: "A powerful, real-time performance monitoring toolkit for Flutter apps. Track FPS, memory, CPU, network, and battery metrics with beautiful visualizations. Built by jamalihassan0307"
version: 1.0.2
homepage: https://github.com/jamalihassan0307/flutter_performance_pulse
repository: https://github.com/jamalihassan0307/flutter_performance_pulse
documentation: https://github.com/jamalihassan0307/flutter_performance_pulse/blob/main/README.md
issue_tracker: https://github.com/jamalihassan0307/flutter_performance_pulse/issues


environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # For charts and visualizations
  fl_chart: ^0.66.2
  # For isolate computations
  compute: ^1.0.2
  # For device info
  device_info_plus: ^9.1.2
  # For battery info
  battery_plus: ^5.0.3
  # For network monitoring
  dio: ^5.4.1
  # For local storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
